# Generated by Django 4.2.1 on 2023-06-01 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='passenger/pfoile-photos/')),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=225)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=225)),
                ('stripe_card_last4', models.CharField(blank=True, max_length=225)),
                ('passenger', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('name', models.CharField(blank=True, default=None, max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255)),
                ('pickup_address', models.CharField(default=None, max_length=255)),
                ('dropoff_address', models.CharField(default=None, max_length=255)),
                ('pickup_lng', models.FloatField(default=0.0)),
                ('pickup_lat', models.FloatField(default=0.0)),
                ('trip_price', models.FloatField(default=0)),
                ('taxi_status', models.CharField(choices=[('booking in proccess', 'Booking in process'), ('arrived', 'Arrived'), ('booked', 'Booked'), ('onboard', 'You are on board'), ('cancelled', 'Trip has been canceled'), ('complete', 'Trip has been completed')], default='booking in proccess', max_length=100)),
                ('passenger', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.passenger')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
