# Generated by Django 4.2.1 on 2023-05-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='user_avatar',
        ),
        migrations.AddField(
            model_name='passenger',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passenger/profile_photo/'),
        ),
    ]
