# Generated by Django 4.2.1 on 2023-10-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytrips',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
