# Generated by Django 4.2.1 on 2023-06-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_passenger_taxi_user_passenegr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxi',
            old_name='user_passenegr',
            new_name='taxi_passenger',
        ),
        migrations.RemoveField(
            model_name='taxi',
            name='name',
        ),
        migrations.RemoveField(
            model_name='taxi',
            name='user',
        ),
    ]
