# Generated by Django 4.2.1 on 2023-05-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_passenger_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
