# Generated by Django 4.2.1 on 2023-05-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_passenger_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='stripe_card_last4',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='passenger',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='passenger',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
