# Generated by Django 4.2.1 on 2023-06-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_passenger_passenger_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='user',
            new_name='passenger',
        ),
    ]
