# Generated by Django 4.2.1 on 2023-06-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_user_passenger_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='passenger',
            new_name='user',
        ),
    ]
