# Generated by Django 4.2.1 on 2023-06-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_passenger_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='accepted_trips',
            field=models.ManyToManyField(blank=True, related_name='booked', to='core.taxi'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cancelled_trips',
            field=models.ManyToManyField(blank=True, related_name='cancelled', to='core.taxi'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='completed_trips',
            field=models.ManyToManyField(blank=True, related_name='completed', to='core.taxi'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='current_trips',
            field=models.ManyToManyField(blank=True, related_name='onboard', to='core.taxi'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_trip_status',
            field=models.CharField(choices=[('no trips', 'No trips'), ('accepted', 'Trip has been accepted'), ('cancelled', 'Trip has been cancelled'), ('onboard', 'Passenger Onboard'), ('no trips', 'No trips')], default='no trips', max_length=255),
        ),
        migrations.RemoveField(
            model_name='driver',
            name='trips_distance_covered',
        ),
        migrations.AddField(
            model_name='driver',
            name='trips_distance_covered',
            field=models.ManyToManyField(default='', related_name='trips_distance_covered', to='core.taxi'),
        ),
    ]
