# Generated by Django 4.2.1 on 2023-05-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_taxicategory_tripsstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxicategory',
            name='choose_taxi_size',
            field=models.CharField(choices=[('five_seater', '5 Seater'), ('sever_seater', ' 7 Seater'), ('eight_seater', ' 8 Seater')], default='five_seater', max_length=20),
        ),
    ]
