# Generated by Django 4.2.1 on 2023-06-21 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_driver_accepted_trips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.driver'),
        ),
    ]
