# Generated by Django 4.2.1 on 2023-06-08 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_rename_passenger_passenger_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxi',
            old_name='taxi_status',
            new_name='taxi_booking_status',
        ),
        migrations.AddField(
            model_name='taxi',
            name='taxi_size',
            field=models.CharField(choices=[('5 Seater', '5 Seater'), ('7 Seater', ' 7 Seater'), ('7 Seater', ' 8 Seater')], default='5 Seater', max_length=10),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='taxi_passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.passenger'),
        ),
    ]
