# Generated by Django 4.2.1 on 2023-06-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_taxi_status_taxi_taxi_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='dropoff_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='taxi',
            name='dropoff_lng',
            field=models.FloatField(default=0.0),
        ),
    ]
