# Generated by Django 4.2.1 on 2023-05-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_taxicategory_choose_taxi_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TripsStatus',
            new_name='TripStatus',
        ),
    ]
