# Generated by Django 4.2.1 on 2023-06-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_taxi_dropoff_lat_taxi_dropoff_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='dropoff_lat',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='dropoff_lng',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='pickup_lat',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='pickup_lng',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='trip_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
