# Generated by Django 4.2.1 on 2023-05-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_tripsstatus_tripstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxicategory',
            name='name',
        ),
    ]
