# Generated by Django 4.2.1 on 2023-06-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_taxi_dropoff_lat_alter_taxi_dropoff_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='distance',
            field=models.FloatField(default=0, null=True),
        ),
    ]
