# Generated by Django 4.2.1 on 2023-05-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_taxicategory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxicategory',
            old_name='choose_taxi_size',
            new_name='name',
        ),
    ]
