# Generated by Django 4.2.1 on 2023-05-29 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_choose_taxi_size_taxicategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxicategory',
            name='name',
            field=models.CharField(choices=[('5 Seater', '5 Seater'), ('7 Seater', ' 7 Seater'), ('7 Seater', ' 8 Seater')], default='5 Seater', max_length=20),
        ),
        migrations.AlterField(
            model_name='tripstatus',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.taxicategory'),
        ),
    ]
