# Generated by Django 4.2.1 on 2023-06-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_taxi_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='distance',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
    ]
