# Generated by Django 4.2.1 on 2023-06-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_taxi_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='taxi_passenger_phone_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
