# Generated by Django 4.2.1 on 2023-05-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_taxicategory_name_alter_tripstatus_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstatus',
            name='number_of_passengers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
