# Generated by Django 4.2.1 on 2023-05-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_tripstatus_number_of_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstatus',
            name='number_of_passengers',
            field=models.IntegerField(default=1),
        ),
    ]
