# Generated by Django 4.2.1 on 2023-05-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_tripstatus_number_of_passengers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripstatus',
            old_name='number_of_passengers',
            new_name='num_of_passengers',
        ),
    ]
