# Generated by Django 4.2.1 on 2023-06-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_taxi_taxi_passneger_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
