# Generated by Django 4.2.1 on 2023-06-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_taxi_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxi',
            name='taxi_fare',
            field=models.FloatField(default=0),
        ),
    ]
