# Generated by Django 4.2.1 on 2023-05-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_number_of_passengers_tripstatus_num_of_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripstatus',
            name='category',
        ),
    ]
