# Generated by Django 4.2.1 on 2023-06-13 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_taxi_duration_taxi_taxi_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='booking_made_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
