# Generated by Django 4.2.1 on 2023-05-29 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_tripstatus_num_of_passengers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TripStatus',
            new_name='Booking',
        ),
        migrations.DeleteModel(
            name='TaxiCategory',
        ),
    ]
