# Generated by Django 4.2.1 on 2023-06-13 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_taxi_booking_made_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTrips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now=True)),
                ('booked_passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.passenger')),
                ('booked_taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.taxi')),
            ],
        ),
    ]
