# Generated by Django 4.2.1 on 2023-05-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_tripstatus_booking_delete_taxicategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booking in proccess', 'Booking in process'), ('arrived', 'Arrived'), ('onboard', 'Passenger on board'), ('cancelled', 'Trip has been canceled'), ('complete', 'Trip has been completed')], default='booking in proccess', max_length=20),
        ),
    ]
