# Generated by Django 4.2.1 on 2023-06-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_mytrips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytrips',
            name='booking_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
