# Generated by Django 4.2.1 on 2023-06-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_booking_made_time_taxi_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='pickup_date',
            field=models.CharField(default='', max_length=500),
        ),
    ]
