# Generated by Django 4.2.1 on 2023-06-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_taxi_pickup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='taxi_booking_status',
            field=models.CharField(choices=[('booking in proccess', 'Booking in progress'), ('arrived', 'Arrived'), ('booked', 'Booked'), ('onboard', 'You are on board'), ('cancelled', 'Trip has been canceled'), ('complete', 'Trip has been completed')], default='booking in proccess', max_length=100),
        ),
    ]
