# Generated by Django 4.2.1 on 2023-06-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_taxi_taxi_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxi',
            old_name='taxi_fare',
            new_name='trip_fare',
        ),
        migrations.RemoveField(
            model_name='taxi',
            name='distance',
        ),
        migrations.AddField(
            model_name='taxi',
            name='trip_distance',
            field=models.FloatField(default=0, null=True),
        ),
    ]
