# Generated by Django 4.2.1 on 2023-06-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_taxi_fare_taxi_trip_fare_remove_taxi_distance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxi',
            old_name='pickup_time',
            new_name='pickup_datetime',
        ),
        migrations.RemoveField(
            model_name='taxi',
            name='pickup_date',
        ),
    ]
