# Generated by Django 4.2.1 on 2023-06-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_taxi_trip_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='trip_distance',
            field=models.FloatField(default=0),
        ),
    ]
