# Generated by Django 4.2.1 on 2023-06-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_taxi_trip_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='trip_distance',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
