# Generated by Django 4.2.1 on 2023-06-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_taxi_trip_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytrips',
            name='cancellation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
