# Generated by Django 4.2.1 on 2023-06-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_mytrips_cancellation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='taxi_booking_status',
            field=models.CharField(choices=[('booking in proccess', 'Booking in progress'), ('arrived', 'Arrived'), ('booked', 'Booked'), ('onboard', 'You are on board'), ('cancelled', 'Trip has been canceled'), ('complete', 'Trip has been completed')], max_length=100),
        ),
    ]
