# Generated by Django 4.2.1 on 2023-06-15 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_taxi_taxi_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytrips',
            name='booking_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mytrips',
            name='cancellation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
