# Generated by Django 4.2.1 on 2023-06-15 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_mytrips_booking_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytrips',
            name='booking_time',
        ),
        migrations.RemoveField(
            model_name='mytrips',
            name='cancellation_time',
        ),
        migrations.AddField(
            model_name='taxi',
            name='booking_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='taxi',
            name='cancellation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='taxi_booking_status',
            field=models.CharField(choices=[('booking in proccess', 'Booking in progress'), ('arrived', 'Arrived'), ('booked', 'Booked'), ('onboard', 'Onboard'), ('cancelled', 'Cancelled'), ('complete', 'Completed')], max_length=100),
        ),
    ]
