# Generated by Django 4.2.1 on 2023-06-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_mytrips_booking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passenger/static/pfoile-photos/'),
        ),
    ]
