# Generated by Django 4.2.1 on 2023-06-16 23:17

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0031_alter_passenger_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.passenger_image_upload),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=core.models.driver_image_upload)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('nta_badge_number', models.CharField(default='N1234', max_length=6)),
                ('vehicle_reg', models.CharField(default='', max_length=100)),
                ('date_of_birth', models.DateTimeField(default=django.utils.timezone.now)),
                ('spsv_license_expirations', models.DateTimeField(default=django.utils.timezone.now)),
                ('roof_sign_number', models.CharField(default='', max_length=10)),
                ('roof_sign_license_expiry', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle_license_disc', models.ImageField(default='', upload_to=core.models.driver_image_upload)),
                ('spsv_license', models.ImageField(default='', upload_to=core.models.driver_image_upload)),
                ('driving_license_number', models.CharField(default='', max_length=200)),
                ('driving_license', models.ImageField(default='', upload_to=core.models.driver_image_upload)),
                ('trips_distance_covered', models.CharField(default='', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('vehicle_make_and_model', models.CharField(default='', max_length=255)),
                ('vehicle_type', models.CharField(choices=[('electric', 'Electric'), ('hybrid', 'Hybrid'), ('petrol', 'Petrol'), ('diesel', 'Diesel')], default='electric', max_length=255)),
                ('driver_trip_status', models.CharField(choices=[('accepted', 'Trip has been accepted'), ('cancelled', 'Trip has been cancelled'), ('onboard', 'Passenger Onboard'), ('no trips', 'No trips')], default='no trips', max_length=255)),
                ('accepted_trips', models.ManyToManyField(blank=True, related_name='accepted_drivers', to='core.mytrips')),
                ('cancelled_trips', models.ManyToManyField(blank=True, related_name='cancelled_drivers', to='core.mytrips')),
                ('completed_trips', models.ManyToManyField(blank=True, related_name='completed_drivers', to='core.mytrips')),
                ('current_trips', models.ManyToManyField(blank=True, related_name='current_drivers', to='core.mytrips')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
