# Generated by Django 4.2.1 on 2023-06-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_taxi_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='stripe_card_last4',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='trip_distance_covered',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
